# Generated by Django 3.0.4 on 2020-04-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Назва тыпу')),
            ],
            options={
                'verbose_name': 'Тып',
                'verbose_name_plural': 'Тыпы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='stones',
            options={'ordering': ['title'], 'verbose_name': 'Камень', 'verbose_name_plural': 'Камяні'},
        ),
        migrations.AlterField(
            model_name='stones',
            name='legend',
            field=models.TextField(blank=True, null=True, verbose_name='Легенда'),
        ),
        migrations.AlterField(
            model_name='stones',
            name='place',
            field=models.TextField(verbose_name='Месцазнаходжанне'),
        ),
        migrations.AlterField(
            model_name='stones',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='stones',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='volumbf.Typ', verbose_name='Тып'),
        ),
    ]
