# Generated by Django 3.0.4 on 2020-04-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0002_auto_20200408_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stones',
            options={'verbose_name': 'Камень', 'verbose_name_plural': 'Камяні'},
        ),
        migrations.AlterUniqueTogether(
            name='stones',
            unique_together={('title', 'place')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='stones',
            order_with_respect_to='typ',
        ),
    ]
