# Generated by Django 3.0.4 on 2020-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0002_auto_20200408_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stones',
            options={'verbose_name': 'Камень', 'verbose_name_plural': 'Камяні'},
        ),
        migrations.AlterUniqueTogether(
            name='stones',
            unique_together={('title', 'place')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='stones',
            order_with_respect_to='typ',
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Аўтар')),
                ('work', models.TextField(verbose_name='Праца')),
                ('sacral_objects', models.ManyToManyField(to='volumbf.Stones', verbose_name="Сакральны аб'ект")),
            ],
            options={
                'verbose_name': 'Узгадка',
                'verbose_name_plural': 'Узгадкі',
                'ordering': ['author'],
                'unique_together': {('author', 'work')},
            },
        ),
    ]
