# Generated by Django 3.0.4 on 2020-04-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0003_auto_20200415_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Аўтар')),
                ('work', models.TextField(verbose_name='Праца')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Дата ўзгадкі')),
                ('sacral_objects', models.ManyToManyField(null=True, to='volumbf.Stones', verbose_name="Сакральны аб'ект")),
            ],
            options={
                'verbose_name': 'Узгадка',
                'verbose_name_plural': 'Узгадкі',
                'ordering': ['author'],
                'unique_together': {('author', 'work')},
            },
        ),
    ]
