# Generated by Django 3.0.4 on 2020-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0004_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentions',
            name='year',
        ),
        migrations.AlterField(
            model_name='mentions',
            name='sacral_objects',
            field=models.ManyToManyField(to='volumbf.Stones', verbose_name="Сакральны аб'ект"),
        ),
    ]
