# Generated by Django 3.0.4 on 2020-04-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0005_auto_20200416_1912'),
        ('volumbf', '0003_auto_20200417_1230'),
    ]

    operations = [
    ]
