# Generated by Django 3.0.4 on 2020-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0008_auto_20200417_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentions',
            options={'ordering': ['work'], 'verbose_name': 'Узгадка', 'verbose_name_plural': 'Узгадкі'},
        ),
        migrations.AlterUniqueTogether(
            name='mentions',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Аўтар')),
                ('publications', models.ManyToManyField(related_name='authors', to='volumbf.Mentions', verbose_name='Аўтары')),
            ],
            options={
                'verbose_name': 'Аўтар',
                'verbose_name_plural': 'Аўтары',
                'ordering': ['author'],
            },
        ),
        migrations.RemoveField(
            model_name='mentions',
            name='author',
        ),
    ]
