# Generated by Django 3.0.4 on 2020-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0009_auto_20200418_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentions',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
