# Generated by Django 3.0.4 on 2020-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0010_mentions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='publications',
            field=models.ManyToManyField(related_name='authors', to='volumbf.Mentions', verbose_name='Публікацыі'),
        ),
    ]
