# Generated by Django 3.0.4 on 2020-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0011_auto_20200423_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='authors', to='volumbf.Mentions', verbose_name='Публікацыі'),
        ),
    ]
