# Generated by Django 3.0.4 on 2020-04-26 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0012_auto_20200424_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='volumbf.Stones')),
            ],
        ),
    ]
