# Generated by Django 3.0.4 on 2020-04-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0013_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Каментар', 'verbose_name_plural': 'Каментары'},
        ),
    ]
