# Generated by Django 2.0.13 on 2020-05-02 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import volumbf.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volumbf', '0015_auto_20200426_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='StonesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=volumbf.models.stones_directory_path_with_uuid)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('stones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volumbf.Stones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
