# Generated by Django 2.0.13 on 2020-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0017_stones_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='stones',
            name='slug',
            field=models.SlugField(default='stone', max_length=250),
        ),
    ]
