# Generated by Django 3.0.4 on 2020-04-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Знята ў час аўтэнтычнага абрада'), (1, 'Мастацкае асэнсаванне'), (2, 'Апрацаваны запіс аўтэнтычнага абраду'), (3, 'Непасрэдная перадача падзеі')], default=0),
        ),
    ]
