# Generated by Django 3.0.4 on 2020-04-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0011_auto_20200423_1848'),
        ('movie', '0002_auto_20200422_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-year', 'title')},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.CharField(max_length=140)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volumbf.Authors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie')),
            ],
            options={
                'unique_together': {('movie', 'author', 'participation')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='creators',
            field=models.ManyToManyField(blank=True, related_name='created_by', through='movie.Role', to='volumbf.Authors'),
        ),
    ]
