# Generated by Django 3.0.4 on 2020-04-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volumbf', '0011_auto_20200423_1848'),
        ('movie', '0003_auto_20200423_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-year', 'title'), 'verbose_name': 'Фільм', 'verbose_name_plural': 'Фільмы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Удзел', 'verbose_name_plural': 'Удзел'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='directed_by', to='volumbf.Authors'),
        ),
        migrations.AlterField(
            model_name='role',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volumbf.Authors', verbose_name='Аўтар'),
        ),
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie', verbose_name='Фільм'),
        ),
    ]
